### ISSUE TITLE
Pantable filters broken after Pandoc upgrade

### ISSUE THREAD

**Issue by alerque** [ickc/pantable#52] opened 2020-10-02 09:41 UTC
I recently upgraded a number of production machines from Pandoc 2.9.2 to 2.10.1. I thought all was well, but it turns out all my jobs that include Pantable at any point are failing. Here is a MWE that illustrates my usage:

~~~markdown
# head

```table
---
alignment: RL
width: [0.5, 0.5]
---
"foo","bar"
```

~~~

```console
$ pandoc -F pantable -t markdwon+pipe_tables-multiline-tables-grid_tables-raw_html < input.md
Error running filter pantable:
Error in $.blocks[1].c: cannot unpack array of length 5 into a tuple of length 6
```

Although I should note that this can be simplified further: just outputting to `-t html` throws the same error, and the YAML table properties don't seem to matter.

**Comment by ickc** [comment] 2020-10-02 10:32
Duplicate of #51.

**Closed** 2020-10-02 10:33 UTC
